services:
  backend:
    build:
      context: backend
    restart: always
    secrets:
      - db-password
    depends_on:
      - db

  db:
    user: root
    image: mariadb:10-focal
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    secrets:
      - db-password
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password


  proxy:
    build:
      context: proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

secrets:
  db-password:
    file: db/password.txt
