services:
  web1:
    build: 
      context: web
    hostname: web1
    ports:
      - 81:5000
    depends_on:
      - redis
      
  web2:
    build: 
      context: web
    hostname: web2
    ports:
      - 82:5000
    depends_on:
      - redis
    
  redis:
    image: redislabs/redismod
    ports:
      - 6379:6379

  proxy:
    build:
      context: proxy
    ports:
      - 80:80
    depends_on:
      - web1
      - web2