services:
  flask-app:
    build:
      context : app
    depends_on:
      - db
  
  db:
    image: mongo
    container_name: mongo
  proxy:
    build:
      context: proxy
    restart: always
    ports:
      - "80:8000"
    depends_on:
      - flask-app