services:
  backend:
    build:
      context: app
    expose:
      - 5000
    restart: always
    secrets:
      - db-password
    networks:
      - app-network
      - db-network
    depends_on:
      - db
  db:
    image: mariadb:10-focal
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    secrets:
      - db-password
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    networks:
      - db-network
  proxy:
    build:
      context: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - app-network
    expose:
      - 3306
      - 33060

secrets:
  db-password:
    file: db/password.txt

networks:
  app-network:
  db-network:
